version: '3.4'

services:
  cko-paymentgateway-webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  cko-banksimulator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
